GrandeTravels/src/GrandeTravels/ViewModels/UpdateCustomerProfileViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace GrandeTravels.ViewModels
{
    public class UpdateCustomerProfileViewModel
    {
        public string Title { get; set; }

        [StringLength(25, MinimumLength = 3, ErrorMessage = "Display name must be between 2 and 50 Characters long")]
        [Required]
        public string DisplayName { get; set; }

        [StringLength(50, MinimumLength = 2, ErrorMessage = "First name must be between 2 and 50 LETTERS long")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "First name must only contain letters")]
        [Required]
        public string FirstName { get; set; }

        [StringLength(50, MinimumLength = 2, ErrorMessage = "Last name must be between 2 and 50 LETTERS long")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Last name must only contain letters")]
        [Required]
        public string LastName { get; set; }


        //[DataType(DataType.EmailAddress, ErrorMessage = "Invalid email address")]
        [RegularExpression(@"^[\w!#$%&'*+\-/=?\^_`{|}~]+(\.[\w!#$%&'*+\-/=?\^_`{|}~]+)*"
            + "@"
            + @"((([\-\w]+\.)+[a-zA-Z]{2,4})|(([0-9]{1,3}\.){3}[0-9]{1,3}))$", ErrorMessage = "Invalid Email")]
        [Required]
        public string Email { get; set; }

        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
            ErrorMessage = "Invalid Australian phone number")]
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }

        [Display(Name = "Display Photo")]
        public string DisplayPhotoPath { get; set; }
        public string SavedStatus { get; set; }
    }
}

GrandeTravels/src/GrandeTravels/Controllers/CustomerProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;

using GrandeTravels.Models;
using GrandeTravels.Services;
using GrandeTravels.ViewModels;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace GrandeTravels.Controllers
{
    public class CustomerProfileController : Controller
    {
        private UserManager<User> _userManager;
        private SignInManager<User> _signInManager;
        private IRepository<CustomerProfile> _customerProfileRepo;

        public CustomerProfileController(UserManager<User> userManager, SignInManager<User> signInManager, IRepository<CustomerProfile> customerProfileRepo)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _customerProfileRepo = customerProfileRepo;
        }

        [HttpGet]
        public async Task<IActionResult> UpdateCustomerProfile()
        {
            UpdateCustomerProfileViewModel vm = new UpdateCustomerProfileViewModel();
            vm.SavedStatus = null;

            try
            {
                User user = await _userManager.FindByNameAsync(User.Identity.Name);
                
                if (user != null)
                {
                    CustomerProfile custProfile = _customerProfileRepo.GetSingle(p => p.UserID == user.Id);

                    if (custProfile != null)
                    {
                        vm.DisplayName = custProfile.DisplayName;
                        vm.FirstName = custProfile.FirstName;
                        vm.LastName = custProfile.LastName;
                        vm.Email = custProfile.Email;
                        vm.Phone = custProfile.Phone;
                        vm.Title = "Update Profile";
                    }
                    else
                    {
                        vm.DisplayName = user.UserName;
                        vm.Title = "Welcome to your new Profile!";
                        
                    }

                    return View(vm);
                }
                else
                {
                    RedirectToAction("SignUp", "Account");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                throw;
            }
            
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> UpdateCustomerProfile(UpdateCustomerProfileViewModel vm)
        {
            vm.SavedStatus = null;

            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByNameAsync(User.Identity.Name);

                CustomerProfile tempProfile = new CustomerProfile();
                tempProfile.DisplayName = vm.DisplayName;
                tempProfile.FirstName = vm.FirstName;
                tempProfile.LastName = vm.LastName;
                tempProfile.Email = vm.Email;
                tempProfile.Phone = vm.Phone;
                tempProfile.UserID = user.Id;

                CustomerProfile custProfile = _customerProfileRepo.GetSingle(p => p.UserID == user.Id);

                try
                {
                    if (custProfile != null)
                    {
                        //keep the existing profile ID
                        custProfile.DisplayName = tempProfile.DisplayName;
                        custProfile.FirstName = tempProfile.FirstName;
                        custProfile.LastName = tempProfile.LastName;
                        custProfile.Email = tempProfile.Email;
                        custProfile.Phone = tempProfile.Phone;

                        _customerProfileRepo.Update(custProfile);
                    }
                    else
                    {
                        _customerProfileRepo.Create(tempProfile);
                    }

                    vm.SavedStatus = "Your detials were successfully saved!";
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    vm.SavedStatus = "Something went wrong with saving your details :/";
                    throw;
                }
            }

            return View(vm);
        }
    }
}

GrandeTravels/src/GrandeTravels/Views/CustomerProfile/UpdateCustomerProfile.cshtml
@model UpdateCustomerProfileViewModel

<h1>@Model.Title</h1>

<form asp-action="UpdateCustomerProfile" asp-controller="CustomerProfile" method="post">

    <div class="form-group">
        <label asp-for="DisplayName"></label>
        <input type="text" asp-for="DisplayName" class="form-control" />
        <span asp-validation-for="DisplayName" class="text-danger"></span>
        <br />
    </div>


    <div class="form-group">
        <label asp-for="FirstName"></label>
        <input type="text" asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
        <br />
    </div>


    <div class="form-group">
        <label asp-for="LastName"></label>
        <input type="text" asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
        <br />
    </div>


    <div class="form-group">
        <label asp-for="Email"></label>
        <input type="text" asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
        <br />
    </div>

    <div class="form-group">
        <label asp-for="Phone"></label>
        <input type="text" asp-for="Phone" class="form-control" />
        <span asp-validation-for="Phone" class="text-danger"></span>
        <br />
    </div>

    <div class="form-group">
        <label asp-for="DisplayPhotoPath"></label>
        <input type="text" asp-for="DisplayPhotoPath" class="form-control" />
        <br />
    </div>

    <div class="text-danger" asp-validation-summary="ModelOnly"></div>
    <h5>@Model.SavedStatus</h5>

    <button type="submit" class="btn btn-danger">Submit</button>
</form>