GrandeTravels/src/GrandeTravels/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;

using GrandeTravels.Models;
using GrandeTravels.Services;
using GrandeTravels.ViewModels;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace GrandeTravels.Controllers
{
    public class ProfileController : Controller
    {
        private UserManager<User> _userManager;
        private SignInManager<User> _signInManager;
        private IRepository<Profile> _profileRepo;
        private IRepository<Booking> _bookingRepo;
        private IRepository<Package> _packageRepo;
        private IHostingEnvironment _hostingEnviro;


        public ProfileController(
            UserManager<User> userManager, 
            SignInManager<User> signInManager, 
            IRepository<Profile> profileRepo,
            IRepository<Booking> bookingRepo,
            IRepository<Package> packageRepo,
            IHostingEnvironment hostingEnviro)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _profileRepo = profileRepo;
            _hostingEnviro = hostingEnviro;
            _bookingRepo = bookingRepo;
            _packageRepo = packageRepo;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ProfileIndexViewModel vm = new ProfileIndexViewModel();

            try
            {
                User user = await _userManager.FindByNameAsync(User.Identity.Name);

                if (user != null)
                {
                    Profile profile = _profileRepo.GetSingle(p => p.UserID == user.Id);

                    //shouldnt be null
                    if (profile == null)
                    {
                        profile = new Profile()
                        {
                            DisplayPhotoPath = "images/user.png",
                            DisplayName = "No Display Name",
                            FirstName = "No Firstname",
                            LastName = "No Lastname",
                            Email = user.Email,
                            Phone = "No Phone",
                            UserID = user.Id
                        };

                        _profileRepo.Create(profile);
                    }

                    vm.DisplayPhotoPath = profile.DisplayPhotoPath;
                    vm.DisplayName = profile.DisplayName;
                    vm.FirstName = profile.FirstName;
                    vm.LastName = profile.LastName;
                    vm.Email = profile.Email;
                    vm.Phone = profile.Phone;

                }
                else
                {
                    RedirectToAction("SignUp", "Account");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                throw;
            }

            return View(vm);

        }

        [HttpGet]
        public async Task<IActionResult> UpdateProfile()
        {
            User user = await _userManager.FindByNameAsync(User.Identity.Name);
            Profile profile = _profileRepo.GetSingle(p => p.UserID == user.Id);

            UpdateProfileViewModel vm = new UpdateProfileViewModel();

            vm.DisplayName = profile.DisplayName;
            vm.FirstName = profile.FirstName;
            vm.LastName = profile.LastName;
            vm.Email = profile.Email;
            vm.Phone = profile.Phone;
            vm.DisplayPhotoPath = profile.DisplayPhotoPath;
            

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProfile(UpdateProfileViewModel vm, IFormFile DisplayPhotoPath)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByNameAsync(User.Identity.Name);
                Profile profile = _profileRepo.GetSingle(p => p.UserID == user.Id);

                profile.DisplayName = vm.DisplayName;
                profile.FirstName = vm.FirstName;
                profile.LastName = vm.LastName;
                profile.Email = vm.Email;
                profile.Phone = vm.Phone;

                if (DisplayPhotoPath != null)
                {
                    string uploadPath = Path.Combine(_hostingEnviro.WebRootPath, "Media\\Profile");
                    string filename = User.Identity.Name + "-" + profile.ID + Path.GetExtension(DisplayPhotoPath.FileName);

                    uploadPath = Path.Combine(uploadPath, filename);


                    using (FileStream fs = new FileStream(uploadPath, FileMode.Create))
                    {
                        DisplayPhotoPath.CopyTo(fs);
                    }

                    string SaveFilename = Path.Combine("Media\\Profile", filename);
                    profile.DisplayPhotoPath = SaveFilename;
                }
                else
                {
                    profile.DisplayPhotoPath = "images/user.png";
                }

                _profileRepo.Update(profile);

                return RedirectToAction("Index");
            }

            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> MyBookings()
        {
            User user = await _userManager.GetUserAsync(HttpContext.User);
            
            IEnumerable<Booking> bookings = _bookingRepo.Query(b => b.UserID == user.Id);
            foreach (var booking in bookings)
            {
                booking.Package = _packageRepo.GetSingle(p => p.ID == booking.PackageID);
            }

            MyBookingsViewModel vm = new MyBookingsViewModel();
            vm.Bookings = bookings;

            return View(vm);
        }
    }
}

GrandeTravels/src/GrandeTravels/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GrandeTravels</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css " />
        <script src="https://code.jquery.com/jquery-3.2.1.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Cinzel|Comfortaa|Julius+Sans+One" rel="stylesheet">
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link href="https://fonts.googleapis.com/css?family=Cinzel|Comfortaa|Julius+Sans+One" rel="stylesheet">
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    @*<nav class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">GrandeTravels</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Package" asp-action="Index">Packages</a></li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a>
                                <form method="post" asp-controller="Account" asp-action="Logout" asp-anti-forgery="true">
                                    <input id="logoutBtn" type="submit" value="Logout" />
                                </form>
                            </a>
                        </li>
                        <li><a asp-area="" asp-controller="Profile" asp-action="UpdateCustomerProfile">Update Profile</a></li>
                        <li><a asp-area="" asp-controller="Booking" asp-action="MyBookings">Bookings</a></li>
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="SignUp">Sign Up</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>*@
    <div id="nav" class="overlay">

        <div class="overlay__content">
            <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            <a asp-area="" asp-controller="Package" asp-action="Index">Packages</a>
            <a asp-area="" asp-controller="Home" asp-action="About">About</a>
            <a href="#">Contact</a>
        </div>
    </div>

    <div class="navToggleBtn" onclick="toggleNav()">
        <div class="hamburger"></div>
    </div>
    <div class="userBtn dropdown">
        <a href="#" class="glyphicon glyphicon-user dropdown-toggle" data-toggle="dropdown"></a>
        
        <ul class="dropdown-menu user-options" >
            <li class="dropdown-header"><a>User Options</a></li>

            @if (User.Identity.IsAuthenticated)
            {
                //<li class="dropdown-header"><a href="#">Logged in as <strong>@User.Identity.Name</strong></a></li>
                <li class=""><a asp-controller="Profile" asp-action="Index">Your Profile</a></li>
                <li class="divider"></li>
                <form asp-action="Logout" asp-controller="Account" method="post"><button id="btn-logout" >Logout</button></form>
            }
            else
            {
                <li><a asp-action="SignUp" asp-controller="Account">Sign Up</a></li>
                <li><a asp-action="Login" asp-controller="Account">Login</a></li>
            }
        </ul>
    </div>

    <div class="container-fluid body-content">

        @RenderBody()
    </div>

    <environment names="Development">
        <script src="~/js/jquery.js"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>